language: rust
sudo: required
dist: bionic

addons:
  apt:
    packages:
      - libssl-dev

before_cache:
  - cargo install cargo-tarpaulin

cache: cargo

before_script:
  - export GRPC_VERSION=1.29.1
  - export PATH="$PATH:$HOME/.cache/bin:$HOME/.cargo/bin"
  - GRPC_HEADER="$HOME/.cache/include/grpc/grpc.h"
  - if [[ ! -f "$GRPC_HEADER" ]] ; then
      (
        git clone -b v$GRPC_VERSION https://github.com/grpc/grpc &&
        cd grpc &&
        git submodule update --init &&
        env prefix=$HOME/.cache make install_c
      );
    fi
  - eval "$(gimme stable)"
  - export CPLUS_INCLUDE_PATH="$HOME/.cache/include"
  - export LD_LIBRARY_PATH="$HOME/.cache/lib"
  - export DYLD_LIBRARY_PATH="$HOME/.cache/lib"
  - export LIBRARY_PATH="$HOME/.cache/lib"
  - export PKG_CONFIG_PATH="$HOME/.cache/lib/pkgconfig"

script:
  - cargo clean
  - cargo build
  - docker-compose up -d
  - cargo test

after_success:
  - cargo tarpaulin --exclude-files src/proto/* --exclude-files tests/* --exclude-files ../../../../../usr/* --ciserver travis-ci --coveralls $TRAVIS_JOB_ID