[package]
name = "xenon-rs"
version = "0.1.0"
description = "Rust bindings to the Xenon interface (gRPC)."
authors = ["Onno Valkering"]
repository = "https://github.com/onnovalkering/xenon-rs"
documentation = "https://docs.rs/xenon-rs"
keywords  = ["xenon", "middleware", "grpc", "hpc", "adaptors"]
license = "MIT"
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
futures = "0.1"
grpcio = { version = "0.4", features = ["openssl"] }
protobuf = "2.8"

[dev-dependencies]
rand = "0.7"

[build-dependencies]
protoc-grpcio = "1.1"