[package]
name = "xenon-rs"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
futures = "0.1"
grpcio = { version = "0.4", features = ["openssl"] }
protobuf = "2.8"

[build-dependencies]
protoc-grpcio = "1.1"