version: "3.5"
services:
  slurm:
    build:
      context: .
      dockerfile: Dockerfile.slurm
    ports:
      - "10022:22"

  xenon:
    build:
      context: .
      dockerfile: Dockerfile.xenon
    ports:
      - "50051:50051"
    privileged: true
    