name: CI

on: [push]

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build project
        run: cargo build -v
      
      - name: Run unit tests
        run: cargo test -v --lib

  integration-tests:
    name: Integration Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Start services
        run: |
          if [ `uname` = 'Darwin' ]; then
              brew install --cask docker
          fi

          docker-compose up -d        

      - name: Build project
        run: cargo build -v

      - name: Run integration tests
        run: cargo test -v --test storage --test compute